import { Banknote, CalendarDays, ChartNoAxesCombined, CircleDollarSign, Fuel, Plus, ReceiptText, TrendingUp, UsersRound } from "lucide-react";
import Link from "next/link";

import { PageHeader } from "@/components/ui/page-header";
import { businessDate } from "@/lib/business-time";
import { listExpenses } from "@/server/repositories/journal-store";
import { getOperationsRepository } from "@/server/repositories/repository-provider";
import { getStaffStore } from "@/server/repositories/staff-store";
import { buildFinanceAnalytics } from "@/server/services/finance-analytics-service";

export const dynamic = "force-dynamic";

const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 });
const categoryNames: Record<string, string> = { maintenance: "Maintenance", electricity: "Electricity", salary: "Salary payment", cleaning: "Cleaning", bank_charges: "Bank charges", other: "Other" };
const formatMoney = (value: string) => money.format(Number(value));

function weekRange(value: string) { const anchor = /^\d{4}-\d{2}-\d{2}$/.test(value) ? new Date(`${value}T00:00:00Z`) : new Date(); const day = anchor.getUTCDay() || 7; const start = new Date(anchor); start.setUTCDate(anchor.getUTCDate() - day + 1); const end = new Date(start); end.setUTCDate(start.getUTCDate() + 6); return [start.toISOString().slice(0, 10), end.toISOString().slice(0, 10)] as const; }

export default async function FinancePage({ searchParams }: { searchParams: Promise<{ month?: string; view?: string; week?: string }> }) {
  const query = await searchParams; const requested = query.month;
  const month = requested && /^\d{4}-(0[1-9]|1[0-2])$/.test(requested) ? requested : businessDate().slice(0, 7);
  const view = query.view === "week" ? "week" : "month"; const week = query.week && /^\d{4}-\d{2}-\d{2}$/.test(query.week) ? query.week : businessDate(); const [from, to] = weekRange(week);
  const [expenses, shifts, staff, payroll] = await Promise.all([listExpenses(), getOperationsRepository().listShifts(), getStaffStore().listStaff(), getStaffStore().listPayroll(month)]);
  const analytics = buildFinanceAnalytics({ month, from: view === "week" ? from : undefined, to: view === "week" ? to : undefined, expenses, shifts, staff, payroll });

  return <main className="page finance-page">
    <PageHeader eyebrow={view === "week" ? `${from} to ${to}` : "Monthly business position"} title="Finance & profitability" description="Daily sales, fuel margin, operating expenses, payroll commitment and staff contribution from closed forecourt records." action={{ label: "Record expense", href: "/finance/expenses/new", icon: <Plus size={16} /> }} />
    <form className="month-command" method="GET"><span><CalendarDays size={18} /><label htmlFor="finance-month"><small>Reporting period</small><strong>Month or Monday–Sunday week</strong></label></span><select defaultValue={view} name="view"><option value="month">Monthly</option><option value="week">Weekly</option></select><input defaultValue={month} id="finance-month" name="month" type="month" /><input defaultValue={week} name="week" type="date" /><button className="button primary" type="submit">View period</button></form>

    <section className="finance-scoreboard reveal reveal-2">
      <article><span><CircleDollarSign size={18} />Revenue</span><strong>{formatMoney(analytics.summary.revenue)}</strong><small>Customer sales from closed days</small></article>
      <article><span><TrendingUp size={18} />Fuel gross profit</span><strong>{formatMoney(analytics.summary.grossMargin)}</strong><small>Selling price less reseller cost</small></article>
      <article><span><ReceiptText size={18} />Operating expenses</span><strong>{formatMoney(analytics.summary.nonSalaryExpenses)}</strong><small>Excludes salary payments</small></article>
      <article><span><UsersRound size={18} />{payroll.length ? "Settled payroll" : "Salary budget"}</span><strong>{formatMoney(payroll.length ? analytics.summary.settledPayrollNet : analytics.summary.salaryBudget)}</strong><small>{formatMoney(payroll.length ? analytics.summary.settledPayrollPaid : analytics.summary.recordedSalaryPayments)} paid · balances stay in Staff</small></article>
      <article className={Number(analytics.summary.estimatedNetProfit) < 0 ? "negative" : "positive"}><span><ChartNoAxesCombined size={18} />Estimated net profit</span><strong>{formatMoney(analytics.summary.estimatedNetProfit)}</strong><small>Gross profit − expenses − monthly salaries</small></article>
    </section>

    <section className="finance-grid reveal reveal-3">
      <article className="panel panel-pad"><div className="panel-header"><div><p className="panel-kicker">Fuel economics</p><h2 className="panel-title">Profit by product</h2></div><Fuel size={19} color="#087665" /></div>{analytics.products.length ? <table className="data-table"><thead><tr><th>Product</th><th>Litres</th><th>Revenue</th><th>Reseller cost</th><th>Gross profit</th></tr></thead><tbody>{analytics.products.map((product) => <tr key={product.productId}><td><span className="table-title">{product.productName}</span></td><td className="mono">{product.litres} L</td><td className="mono">{formatMoney(product.revenue)}</td><td className="mono">{formatMoney(product.cost)}</td><td className="mono profit-value">{formatMoney(product.grossProfit)}</td></tr>)}</tbody></table> : <p className="empty-state">Close a business day in {month} to calculate product profit.</p>}</article>
      <article className="panel panel-pad"><div className="panel-header"><div><p className="panel-kicker">Where money went</p><h2 className="panel-title">Expense breakdown</h2></div><ReceiptText size={19} color="#087665" /></div>{analytics.expenseCategories.length ? <div className="expense-breakdown">{analytics.expenseCategories.map((item) => <div key={item.category}><span><strong>{categoryNames[item.category] ?? item.category}</strong><small>{item.category === "salary" ? "Tracked against payroll" : "Operating expense"}</small></span><b>{formatMoney(item.amount)}</b></div>)}</div> : <p className="empty-state">No expenses recorded for this month.</p>}<Link className="button soft finance-add" href="/finance/expenses/new"><Plus size={14} />Add expense</Link></article>
    </section>

    <section className="panel panel-pad reveal reveal-4 finance-table-panel"><div className="panel-header"><div><p className="panel-kicker">Day-wise ledger</p><h2 className="panel-title">Daily profit position</h2></div><span className="status-pill healthy">{analytics.days.length} recorded days</span></div>{analytics.days.length ? <table className="data-table"><thead><tr><th>Business date</th><th>Closed shifts</th><th>Revenue</th><th>Fuel gross profit</th><th>Operating expenses</th><th>Salary paid</th><th>Profit before salary budget</th></tr></thead><tbody>{analytics.days.map((day) => <tr key={day.businessDate}><td><Link className="table-title" href={`/finance/day/${day.businessDate}`}>{day.businessDate}</Link></td><td>{day.shifts}</td><td className="mono">{formatMoney(day.revenue)}</td><td className="mono">{formatMoney(day.grossMargin)}</td><td className="mono">{formatMoney(day.expenses)}</td><td className="mono">{formatMoney(day.salaryPayments)}</td><td className={`mono ${Number(day.operatingProfitBeforeSalary) < 0 ? "loss-value" : "profit-value"}`}>{formatMoney(day.operatingProfitBeforeSalary)}</td></tr>)}</tbody></table> : <p className="empty-state">There are no sales or expenses for {month}.</p>}</section>

    <section className="panel panel-pad reveal reveal-4 finance-table-panel"><div className="panel-header"><div><p className="panel-kicker">Live, as they&apos;re saved</p><h2 className="panel-title">Completed pump-shifts</h2></div><span className="status-pill healthy">{analytics.pumpShifts.length} completed</span></div>{analytics.pumpShifts.length ? <table className="data-table"><thead><tr><th>Date</th><th>Pump</th><th>Employee</th><th>Shift</th><th>Litres</th><th>Revenue</th><th>Collections entered</th><th>Variance</th></tr></thead><tbody>{analytics.pumpShifts.map((entry) => <tr key={entry.id}><td><Link className="table-title" href={`/finance/day/${entry.businessDate}`}>{entry.businessDate}</Link></td><td>{entry.pumpLabel}</td><td>{entry.staffName}</td><td>{entry.shiftStartTime && entry.shiftEndTime ? `${entry.shiftStartTime}–${entry.shiftEndTime}` : "—"}</td><td className="mono">{entry.litresSold} L</td><td className="mono">{formatMoney(entry.expectedSalesValue)}</td><td className="mono">{formatMoney(entry.accountedTender)}</td><td className={`mono ${Number(entry.tenderVariance) < 0 ? "loss-value" : "profit-value"}`}>{formatMoney(entry.tenderVariance)}</td></tr>)}</tbody></table> : <p className="empty-state">Pump-shifts appear here the moment an employee&apos;s shift is completed on Today&apos;s page.</p>}</section>

    <section className="panel panel-pad reveal reveal-4 finance-table-panel"><div className="panel-header"><div><p className="panel-kicker">Totalizer-attributed performance</p><h2 className="panel-title">Employee contribution</h2></div><UsersRound size={19} color="#087665" /></div>{analytics.staff.length ? <table className="data-table"><thead><tr><th>Employee</th>{analytics.products.map((product) => <th key={product.productId}>{product.productName}</th>)}<th>Total litres</th><th>Revenue generated</th><th>Gross profit contributed</th></tr></thead><tbody>{analytics.staff.map((person) => <tr key={person.staffId}><td><span className="table-title">{person.staffName}</span></td>{analytics.products.map((product) => <td className="mono" key={product.productId}>{person.productLitres[product.productId] ?? "0.000"} L</td>)}<td className="mono">{person.litres} L</td><td className="mono">{formatMoney(person.revenue)}</td><td className="mono profit-value">{formatMoney(person.grossProfit)}</td></tr>)}</tbody></table> : <p className="empty-state">Employee contribution appears after a day with assigned operators is closed.</p>}<p className="finance-footnote">Every litre is attributed to the operator responsible for that nozzle side.</p></section>

    <section className="panel panel-pad reveal reveal-4 finance-table-panel"><div className="panel-header"><div><p className="panel-kicker">Immutable daily rate snapshots</p><h2 className="panel-title">Reseller &amp; customer price history</h2></div><Fuel size={19} color="#087665" /></div>{analytics.prices.length ? <table className="data-table"><thead><tr><th>Date</th><th>Fuel</th><th>Reseller price</th><th>Market/customer price</th><th>Margin per litre</th></tr></thead><tbody>{analytics.prices.map((price) => <tr key={`${price.businessDate}:${price.productId}`}><td>{price.businessDate}</td><td>{price.productName}</td><td className="mono">{formatMoney(price.resellerPrice)}</td><td className="mono">{formatMoney(price.customerPrice)}</td><td className="mono profit-value">{formatMoney(price.marginPerLitre)}</td></tr>)}</tbody></table> : <p className="empty-state">Price history appears after a day is closed.</p>}<div className="staff-drill-links">{analytics.staff.map((person) => <Link className="button soft" href={`/staff/${person.staffId}?month=${month}`} key={person.staffId}>Open {person.staffName}&apos;s daily record</Link>)}</div></section>

    <section className="panel panel-pad reveal reveal-4 finance-table-panel"><div className="panel-header"><div><p className="panel-kicker">Transaction detail</p><h2 className="panel-title">Expense ledger</h2></div><Banknote size={19} color="#087665" /></div>{analytics.expenses.length ? <table className="data-table"><thead><tr><th>Date</th><th>Category</th><th>Note</th><th>Paid through</th><th>Amount</th></tr></thead><tbody>{analytics.expenses.map((expense) => <tr key={expense.id}><td>{expense.date}</td><td>{categoryNames[expense.category] ?? expense.category}</td><td>{expense.note}</td><td>{expense.paymentMethod.toUpperCase()}</td><td className="mono">{formatMoney(expense.amount)}</td></tr>)}</tbody></table> : <p className="empty-state">No expenses recorded for this period.</p>}</section>
  </main>;
}
